2020-03-14 15:24:55,653 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.2
2020-03-14 15:24:55,654 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-03-14-15-24-55-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-03-14 15:24:55,654 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2020-03-14 15:24:55,654 : INFO : Machine : Machine path: E:\mpf\wows\wows
2020-03-14 15:24:55,654 : INFO : Machine : Platform: win32
2020-03-14 15:24:55,654 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2020-03-14 15:24:55,654 : INFO : Machine : Python version: 3.6.4 (64-bit)
2020-03-14 15:24:55,654 : INFO : Machine : Machine config file #1: config.yaml
2020-03-14 15:24:55,655 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a7e9e9e882fa7eca7cb0ba00eaf15121.mpf_cache
2020-03-14 15:24:55,662 : INFO : Machine : Initialise MPF.
2020-03-14 15:24:55,897 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,932 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2020-03-14 15:24:55,932 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.2', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,932 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.2, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,932 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,933 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,933 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,933 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,933 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,933 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2020-03-14 15:24:55,933 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-03-14 15:24:55,965 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2020-03-14 15:24:55,971 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\4aeaa69609f53d9b71d1dbbedd434b0b.mpf_cache
2020-03-14 15:24:55,973 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1e6cc6775e87a3e14ded8d45fd065b10.mpf_cache
2020-03-14 15:24:55,975 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\fa1d48c05f4d8fd05f0b267836a1ac4f.mpf_cache
2020-03-14 15:24:55,977 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\2242affd3e515f08e26d4d5b365e866b.mpf_cache
2020-03-14 15:24:55,979 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\edfeac6524e6d1874b234b23d854175f.mpf_cache
2020-03-14 15:24:55,981 : WARNING : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\modes\detonation\config\detonation.yaml
2020-03-14 15:24:55,981 : INFO : ConfigProcessor : Loading config from file E:\mpf\wows\wows\modes\detonation\config\detonation.yaml.
2020-03-14 15:24:55,991 : INFO : ConfigProcessor : Loading config: E:\mpf\wows\wows\modes\detonation\config\detonation.yaml
2020-03-14 15:24:55,991 : INFO : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\fff0d16f8200200b52cd28c2ea815f12.mpf_cache
2020-03-14 15:24:55,993 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\6e6d4708a613edd7635d35a6961997f3.mpf_cache
2020-03-14 15:24:55,995 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\fbcc5772262340622f93ebd98450e45f.mpf_cache
2020-03-14 15:24:55,997 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d01089fe8a4c8b32515bd43f8cd9fd8b.mpf_cache
2020-03-14 15:24:55,999 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2020-03-14 15:24:56,003 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\fa61b88f86d6e414c9b51ac1d3e19568.mpf_cache
2020-03-14 15:24:56,005 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a6527a592b6034dbfea56fdf726c3822.mpf_cache
2020-03-14 15:24:56,007 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\bafdfa3518b80fac5c67bbc1ea3da4f8.mpf_cache
2020-03-14 15:24:56,009 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\79b69aca05077178b8904472f0120320.mpf_cache
2020-03-14 15:24:56,011 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\f6b4884431efff4cb2e21d23d2c7b801.mpf_cache
2020-03-14 15:24:56,013 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\97f63c0afcbce8d9df7044fccf1035a4.mpf_cache
2020-03-14 15:24:56,015 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\2f7452aae1b2779bb4a1388fc419c0c8.mpf_cache
2020-03-14 15:24:56,017 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5dbeda7d2775496a54d206d506904281.mpf_cache
2020-03-14 15:24:56,019 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\f9a57b3955e1480227d6e8589f6567c4.mpf_cache
2020-03-14 15:24:56,025 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ictionary.",)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:99
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ictionary.",)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:99>
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 102, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 110, in _load_device_modules
    self.machine.mode_controller.create_mode_devices()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 85, in create_mode_devices
    mode.create_mode_devices()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 423, in create_mode_devices
    collection.name, {device: settings})
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 150, in create_devices
    device_name), 3, context=collection_name + "." + device_name)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\logging.py", line 166, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name, context, self._url_base)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in DeviceManager: Device 'switch' does not have a valid config. Expected a dictionary. Context: shots.switch Error Code: CFE-DeviceManager-3 (https://docs.missionpinball.org/en/0.53/logs/CFE-DeviceManager-3.html)
2020-03-14 15:24:56,027 : INFO : Machine : Starting the main run loop.
2020-03-14 15:24:56,028 : INFO : Machine : Shutting down...
2020-03-14 15:24:56,030 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-03-14 15:24:56,031 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 102, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 110, in _load_device_modules
    self.machine.mode_controller.create_mode_devices()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 85, in create_mode_devices
    mode.create_mode_devices()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 423, in create_mode_devices
    collection.name, {device: settings})
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 150, in create_devices
    device_name), 3, context=collection_name + "." + device_name)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\logging.py", line 166, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name, context, self._url_base)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in DeviceManager: Device 'switch' does not have a valid config. Expected a dictionary. Context: shots.switch Error Code: CFE-DeviceManager-3 (https://docs.missionpinball.org/en/0.53/logs/CFE-DeviceManager-3.html)
2020-03-14 15:24:56,032 : INFO : root : MPF run loop ended.
