2020-02-04 22:18:58,918 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.68
2020-02-04 22:18:58,919 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-02-04-22-18-58-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-02-04 22:18:58,919 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2020-02-04 22:18:58,919 : INFO : Machine : Machine path: E:\mpf\wows\wows
2020-02-04 22:18:58,919 : INFO : Machine : Platform: win32
2020-02-04 22:18:58,919 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2020-02-04 22:18:58,919 : INFO : Machine : Python version: 3.6.4 (64-bit)
2020-02-04 22:18:58,919 : INFO : Machine : Machine config file #1: config.yaml
2020-02-04 22:18:58,920 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a7e9e9e882fa7eca7cb0ba00eaf15121.mpf_cache
2020-02-04 22:18:58,922 : INFO : Machine : Initialise MPF.
2020-02-04 22:18:59,441 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,476 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2020-02-04 22:18:59,476 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.68', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,476 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.68, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,476 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,477 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,477 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,477 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,477 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,477 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2020-02-04 22:18:59,477 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-02-04 22:18:59,507 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1e6cc6775e87a3e14ded8d45fd065b10.mpf_cache
2020-02-04 22:18:59,510 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\6e6d4708a613edd7635d35a6961997f3.mpf_cache
2020-02-04 22:18:59,512 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1068177614fe5a40fc2c1e1b0504468c.mpf_cache
2020-02-04 22:18:59,514 : WARNING : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml
2020-02-04 22:18:59,514 : INFO : ConfigProcessor : Loading config from file E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml.
2020-02-04 22:18:59,526 : INFO : ConfigProcessor : Loading config: E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml
2020-02-04 22:18:59,527 : INFO : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\2f7452aae1b2779bb4a1388fc419c0c8.mpf_cache
2020-02-04 22:18:59,529 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2020-02-04 22:18:59,533 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a6527a592b6034dbfea56fdf726c3822.mpf_cache
2020-02-04 22:18:59,535 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2020-02-04 22:18:59,539 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\f9a57b3955e1480227d6e8589f6567c4.mpf_cache
2020-02-04 22:18:59,541 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\4aeaa69609f53d9b71d1dbbedd434b0b.mpf_cache
2020-02-04 22:18:59,568 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2020-02-04 22:18:59,569 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>)
2020-02-04 22:18:59,569 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>)
2020-02-04 22:18:59,569 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>)
2020-02-04 22:18:59,569 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>)
2020-02-04 22:18:59,569 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>)
2020-02-04 22:18:59,569 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>)
2020-02-04 22:18:59,574 : ERROR : asyncio : Exception in callback EventManager._done(<Task finishe...'start'}}]",)>)
handle: <Handle EventManager._done(<Task finishe...'start'}}]",)>)>
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 695, in _done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 612, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 96, in initialise_modes
    mode.initialise_mode()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 576, in initialise_mode
    **item.kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_player.py", line 133, in process_mode_config
    config = self.validate_config(config)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_player.py", line 105, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\config_players\device_config_player.py", line 43, in validate_config_entry
    name, self.show_section, settings))
AssertionError: Invalid settings for player lock_lit_start_light:shows [{'lock_lit_start_1_light_show': {'action': 'start'}}, {'lock_lit_start_2_light_show': {'action': 'start'}}]
2020-02-04 22:18:59,578 : INFO : Machine : Starting the main run loop.
2020-02-04 22:18:59,584 : INFO : Machine : Shutting down...
2020-02-04 22:18:59,584 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-02-04 22:18:59,586 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 695, in _done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 612, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 96, in initialise_modes
    mode.initialise_mode()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 576, in initialise_mode
    **item.kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_player.py", line 133, in process_mode_config
    config = self.validate_config(config)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_player.py", line 105, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\config_players\device_config_player.py", line 43, in validate_config_entry
    name, self.show_section, settings))
AssertionError: Invalid settings for player lock_lit_start_light:shows [{'lock_lit_start_1_light_show': {'action': 'start'}}, {'lock_lit_start_2_light_show': {'action': 'start'}}]
2020-02-04 22:18:59,588 : INFO : root : MPF run loop ended.
